language: java
sudo: true
arch: arm64

jdk:
  - openjdk11
script: "mvn clean package"

before_install:
  - sudo apt install maven

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    - 156125813@qq.com