language: java
sudo: true

jdk:
  - openjdk11
script: "mvn clean package"

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    - 156125813@qq.com