language: java
sudo: true
arch: arm64

jdk:
  - openjdk11
script: "./gradlew clean build jar"

before_install:
  - sudo apt install openjfx
  - chmod 777 ./gradlew

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    - 156125813@qq.com