language: java
sudo: true
arch: arm64

os:
  - linux

jdk:
  - openjdk11
script: "./gradlew clean build jar"

before_install:
  - sudo apt install openjfx
  - chmod 777 ./gradlew

branches:
  only:
    - dev

cache:
  directories:
    - '$HOME/.gradle'

notifications:
  email:
    - 156125813@qq.com